export const SubMenuCmsData = [
  {id: 1, name: 'Components', parentId: 1, icon:"\\e619" , class: 'simple-icon-event'},
  {id: 1, name: 'Default', parentId: 1, class: 'simple-icon-rocket',  icon: "\\e05c"},
  {id: 2, name: 'Analytics', parentId: 1, class: 'simple-icon-pie-chart',  icon: "\\e05e"},
  {id: 3, name: 'Ecommerce', parentId: 1, class: 'simple-icon-basket-loaded',  icon: "\\e05d"},
  {id: 4, name: 'Content', parentId: 1, class: 'simple-icon-doc',  icon: "\\e085"},
  {id: 6, name: 'Layouts', parentId: 1, class: 'simple-icon-check', icon:"\\e080"},
  {id: 7, name: 'Validation', parentId: 1, class: 'simple-icon-magic-wand', icon:"\\e017"},
  {id: 8, name: 'Wizard', parentId: 2, class: 'simple-icon-screen-desktop', icon:"\\e011"},
  {id: 9, name: 'Full Page UI', parentId: 2, class: 'simple-icon-mouse', icon:"\\e015"},
  {id: 10, name: 'Scrollable', parentId: 2, class: 'simple-icon-notebook', icon:"\\e013"},
  {id: 11, name: 'Pagination', parentId: 2, class: 'simple-icon-grid', icon:"\\e06a"},
  {id: 12, name: 'Library', parentId: 3, class: 'simple-icon-picture',  icon: "\\e032"},
  {id: 13, name: 'Todo', parentId: 3, class: 'simple-icon-check',  icon: "\\e080"},
  {id: 14, name: 'Survey', parentId: 3, class: 'simple-icon-calculator',  icon: "\\e049"},
  {id: 15, name: 'Chat', parentId: 3, class: 'simple-icon-bubbles', icon: "\\e04a"},
  {id: 16, name: 'Default', parentId: 4, class: 'simple-icon-bell', icon:"\\e027"},
  {id: 17, name: 'Default', parentId: 4, class: 'simple-icon-bell', icon:"\\e027"},
  {id: 18, name: 'Alerts', parentId: 4, class: 'simple-icon-badge', icon:"\\e028"},
  {id: 19, name: 'Badges', parentId: 4, class: 'simple-icon-control-play', icon:"\\e071"},
  {id: 20, name: 'Buttons', parentId: 4, class: 'simple-icon-layers', icon:"\\e034"},
  {id: 21, name: 'Cards', parentId: 4, class: 'simple-icon-picture', icon:"\\e032"},
  {id: 22, name: 'Carousel', parentId: 4, class: 'simple-icon-chart', icon:"\\e077"},
  {id: 23, name: 'Charts', parentId: 4, class: 'simple-icon-arrow-up', icon:"\\e607"},
  {id: 24, name: 'Collapse', parentId: 4, class: 'simple-icon-arrow-down', icon:"\\e604"},
  {id: 25, name: 'Dropdowns', parentId: 4, class: 'simple-icon-book-open', icon:"\\e04c"},
  {id: 26, name: 'Editors', parentId: 4, class: 'simple-icon-star', icon:"\\e09b"},
  {id: 27, name: 'Icons', parentId: 4, class: 'simple-icon-note', icon:"\\e060"},
  {id: 28, name: 'Input Groups', parentId: 4, class: 'simple-icon-screen-desktop', icon:"\\e011"},
  {id: 29, name: 'Jumbotron', parentId: 4, class: 'simple-icon-docs', icon:"\\e040"},
  {id: 30, name: 'Modal', parentId: 4, class: 'simple-icon-cursor', icon:"\\e06e"},
  {id: 31, name: 'Navigation', parentId: 4, class: 'simple-icon-cursor', icon:"\\e619"},
  {id: 32, name: 'Popover & Tooltip', parentId: 4, class: 'simple-icon-pin', icon:"\\e619"},
  {id: 33, name: 'Sortable', parentId: 4, class: 'simple-icon-shuffle', icon:"\\e619"},
  {id: 34, name: 'Table', parentId: 4, class: 'simple-icon-grid', icon:"\\e619"},
  {id: 35, name: 'Default', parentId: 5, class: 'simple-icon-control-pause', icon:"\\e072"},
  {id: 36, name: 'Subhidden', parentId: 5, class: 'simple-icon-arrow-left', icon:"\\e605"},
  {id: 37, name: 'Hidden', parentId: 5, class: 'simple-icon-control-start', icon:"\\e06f"},
  {id: 38, name: 'Mainhidden', parentId: 5, class: 'simple-icon-control-rewind', icon:"\\e070"},
  {id: 39, name: 'Sub Level', parentId: 5, class: 'simple-icon-layers', icon:"\\e034"},
  {id: 40, name: 'Another Level', parentId: 5, class: 'simple-icon-arrow-down', icon:"\\e604"},
  {id: 41, name: 'Sub Level', parentId: 5, class: 'simple-icon-layers', icon:"\\e034"},
]